services:
  api-aemud:
    container_name: apiaemudcontainer
    build:
      context: .
      args:
        CONTAINER_PORT: ${SERV_PORT}
    image: api-aemud:v1
    restart: always
    env_file:
      - ${ENV_FILE}
    ports:
      - "${SERV_PORT}:${SERV_PORT}"
    depends_on:
      - aemuddb
    networks:
      - aemudnet
  aemuddb:
    image: mysql:8.0
    container_name: aemud-db-cont
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passer123
      MYSQL_DATABASE: aemud
    ports:
      - "3306:3306"
    networks:
      - aemudnet

networks:
  aemudnet:
    driver: bridge