SEV_PORT: 8081
ACTIVE_PROFILE: dev
DBMS: postgresql
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: aemud
DB_PASSWORD: '#Wollaj@1'
DB_USERNAME: postgres
JDBC_DRIVER: org.postgresql.Driver
DIALECT: org.hibernate.dialect.PostgreSQLDialect