# JWT
jwt:
  secret:${JWT_SECRET}


server:
  error:
    path: /error
    whitelabel:
      enabled: true
  port: ${SEV_PORT:8080}
  servlet:
    context-path: /aemud/api/v1

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:${DBMS}://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    driver-class-name: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    database-platform:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DIALECT:org.hibernate.dialect.MySQL8Dialect}
        format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false
logging:
  level:
    org:
      springframework:
        web:
          cors: DEBUG