#serveur config
SEV_PORT: 8888
ACTIVE_PROFILE: prod

#database config
DBMS: mysql
DB_HOST: localhost
DB_PORT: 3306
DB_NAME: aemud
DB_PASSWORD: Wollaj@1
DB_USERNAME: root

#ui config

# UI_APP_URL: http://localhost:4200
