CREATE TABLE app_user
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username              VARCHAR(255)                            NOT NULL,
    password              VARCHAR(255),
    locked                BOOLEAN                                 NOT NULL,
    force_password_change BOOLEAN                                 NOT NULL,
    member_id             VARCHAR(255),
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE TABLE app_user_roles
(
    app_user_id BIGINT NOT NULL,
    roles_id    BIGINT NOT NULL
);

CREATE TABLE bourse
(
    id      VARCHAR(255) NOT NULL,
    lebelle VARCHAR(255),
    montant DOUBLE PRECISION,
    CONSTRAINT pk_bourse PRIMARY KEY (id)
);

CREATE TABLE club
(
    id   VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_club PRIMARY KEY (id)
);

CREATE TABLE commission
(
    id   VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_commission PRIMARY KEY (id)
);

CREATE TABLE contribution
(
    id          VARCHAR(255) NOT NULL,
    member_id   VARCHAR(255) NOT NULL,
    session_id  VARCHAR(255),
    month       date,
    amount_due  DOUBLE PRECISION,
    amount_paid DOUBLE PRECISION,
    status      SMALLINT,
    CONSTRAINT pk_contribution PRIMARY KEY (id)
);

CREATE TABLE member
(
    id                    VARCHAR(255) NOT NULL,
    bourse_id             VARCHAR(255),
    user_id               BIGINT,
    name                  VARCHAR(255),
    firstname             VARCHAR(255),
    nationality           VARCHAR(255),
    birthday              date,
    marital_status        VARCHAR(255),
    gender                VARCHAR(255),
    legacy_institution    VARCHAR(255),
    bac_series            VARCHAR(255),
    bac_mention           VARCHAR(255),
    year_of_bac           VARCHAR(255),
    aemud_courses         VARCHAR(255),
    other_courses         VARCHAR(255),
    participated_activity VARCHAR(255),
    politic_organisation  VARCHAR(255),
    adhesion_date         TIMESTAMP WITHOUT TIME ZONE,
    institution_name      VARCHAR(255),
    studies_domain        VARCHAR(255),
    studies_level         VARCHAR(255),
    number_phone          VARCHAR(255) NOT NULL,
    email                 VARCHAR(255) NOT NULL,
    address_in_dakar      VARCHAR(255),
    holiday_address       VARCHAR(255),
    address_to_campus     VARCHAR(255),
    CONSTRAINT pk_member PRIMARY KEY (id)
);

CREATE TABLE member_person_to_calls
(
    member_id                            VARCHAR(255) NOT NULL,
    person_to_call_name                  VARCHAR(255),
    person_to_call_firstname             VARCHAR(255),
    person_to_call_required_number_phone VARCHAR(255),
    person_to_call_optional_number_phone VARCHAR(255),
    relationship                         VARCHAR(255)
);

CREATE TABLE membre_club
(
    club_id   VARCHAR(255) NOT NULL,
    membre_id VARCHAR(255) NOT NULL
);

CREATE TABLE membre_commission
(
    commission_id VARCHAR(255) NOT NULL,
    membre_id     VARCHAR(255) NOT NULL
);

CREATE TABLE month
(
    id           VARCHAR(255) NOT NULL,
    month_name   VARCHAR(255),
    month_number INTEGER      NOT NULL,
    CONSTRAINT pk_month PRIMARY KEY (id)
);

CREATE TABLE password_reset_token
(
    id          VARCHAR(255) NOT NULL,
    token       VARCHAR(255),
    email       VARCHAR(255) NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    used        BOOLEAN      NOT NULL,
    CONSTRAINT pk_passwordresettoken PRIMARY KEY (id)
);

CREATE TABLE payement
(
    id           VARCHAR(255) NOT NULL,
    amount       DOUBLE PRECISION,
    payment_date date,
    pay_methode  SMALLINT,
    CONSTRAINT pk_payement PRIMARY KEY (id)
);

CREATE TABLE payement_contributions
(
    payement_id      VARCHAR(255) NOT NULL,
    contributions_id VARCHAR(255) NOT NULL
);

CREATE TABLE recipient_template
(
    id            VARCHAR(255) NOT NULL,
    template_name VARCHAR(255),
    CONSTRAINT pk_recipienttemplate PRIMARY KEY (id)
);

CREATE TABLE registration
(
    id                  VARCHAR(255) NOT NULL,
    member_id           VARCHAR(255) NOT NULL,
    session_id          VARCHAR(255) NOT NULL,
    date_inscription    date,
    registration_type   VARCHAR(255),
    status_payment      BOOLEAN      NOT NULL,
    registration_status VARCHAR(255),
    CONSTRAINT pk_registration PRIMARY KEY (id)
);

CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE session
(
    id         VARCHAR(255) NOT NULL,
    session    INTEGER,
    is_current BOOLEAN      NOT NULL,
    CONSTRAINT pk_session PRIMARY KEY (id)
);

CREATE TABLE sms_model
(
    id         VARCHAR(255) NOT NULL,
    model_name VARCHAR(255),
    sms_model  VARCHAR(255),
    CONSTRAINT pk_smsmodel PRIMARY KEY (id)
);

ALTER TABLE app_user
    ADD CONSTRAINT uc_app_user_username UNIQUE (username);

ALTER TABLE member
    ADD CONSTRAINT uc_member_email UNIQUE (email);

ALTER TABLE member
    ADD CONSTRAINT uc_member_numberphone UNIQUE (number_phone);

ALTER TABLE payement_contributions
    ADD CONSTRAINT uc_payement_contributions_contributions UNIQUE (contributions_id);

ALTER TABLE app_user
    ADD CONSTRAINT FK_APP_USER_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id);

ALTER TABLE contribution
    ADD CONSTRAINT FK_CONTRIBUTION_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id);

ALTER TABLE contribution
    ADD CONSTRAINT FK_CONTRIBUTION_ON_SESSION FOREIGN KEY (session_id) REFERENCES session (id);

ALTER TABLE member
    ADD CONSTRAINT FK_MEMBER_ON_BOURSE FOREIGN KEY (bourse_id) REFERENCES bourse (id);

ALTER TABLE member
    ADD CONSTRAINT FK_MEMBER_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id);

ALTER TABLE registration
    ADD CONSTRAINT FK_REGISTRATION_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id);

ALTER TABLE registration
    ADD CONSTRAINT FK_REGISTRATION_ON_SESSION FOREIGN KEY (session_id) REFERENCES session (id);

ALTER TABLE app_user_roles
    ADD CONSTRAINT fk_appuserol_on_role FOREIGN KEY (roles_id) REFERENCES role (id);

ALTER TABLE app_user_roles
    ADD CONSTRAINT fk_appuserol_on_user FOREIGN KEY (app_user_id) REFERENCES app_user (id);

ALTER TABLE member_person_to_calls
    ADD CONSTRAINT fk_member_persontocalls_on_member FOREIGN KEY (member_id) REFERENCES member (id);

ALTER TABLE membre_club
    ADD CONSTRAINT fk_memclu_on_club FOREIGN KEY (club_id) REFERENCES club (id);

ALTER TABLE membre_club
    ADD CONSTRAINT fk_memclu_on_member FOREIGN KEY (membre_id) REFERENCES member (id);

ALTER TABLE membre_commission
    ADD CONSTRAINT fk_memcom_on_commission FOREIGN KEY (commission_id) REFERENCES commission (id);

ALTER TABLE membre_commission
    ADD CONSTRAINT fk_memcom_on_member FOREIGN KEY (membre_id) REFERENCES member (id);

ALTER TABLE payement_contributions
    ADD CONSTRAINT fk_paycon_on_contribution FOREIGN KEY (contributions_id) REFERENCES contribution (id);

ALTER TABLE payement_contributions
    ADD CONSTRAINT fk_paycon_on_payement FOREIGN KEY (payement_id) REFERENCES payement (id);