# JWT
app:
  jwtSecret: ${JWT_SECRET} # Doit correspondre à @Value("${app.jwtSecret}")
  jwtExpirationMs: ${JWT_EXPIRATION}

server:
  error:
    path: /error
    whitelabel:
      enabled: true
  port: ${SEV_PORT:8080}
  servlet:
    context-path: /aemud/api/v1
  # address: 192.168.233.191

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:${DBMS}://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    driver-class-name: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    database-platform:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DIALECT:org.hibernate.dialect.MySQL8Dialect}
        format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
logging:
  level:
    org:
      springframework:
        web: DEBUG