#serveur config
SEV_PORT: 8081
ACTIVE_PROFILE: prod

#database config
DBMS: postgresql
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: aemud
DB_PASSWORD: '#Wollaj@1'
DB_USERNAME: postgres
JWT_SECRET: "KmDWmBsu4p8ZVN2194WtSSx17oqr7q0sL0+SSLIkoPI="
JWT_EXPIRATION: 1800000
JDBC_DRIVER: org.postgresql.Driver
DIALECT: org.hibernate.dialect.PostgreSQLDialect
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: boubacarcidi77@gmail.com
EMAIL_PASSWORD: rxpe kxxz msts ucfo
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}
